version = 1

[[annotations]]
SPDX-FileCopyrightText = "2025 Potsdam Institute for Climate Impact Research (PIK)"
SPDX-License-Identifier = "BSD-2-Clause"
path = [
  ".lintr",
  ".Rbuildignore",
  "CITATION.cff",
  "CRAN-SUBMISSION",
  "DESCRIPTION",
  "inst/extdata/country2iso.csv",
  "inst/extdata/iso_country.csv",
  "inst/extdata/ISOhistorical.csv",
  "inst/extdata/pop2015.rds",
  "inst/extdata/regionmapping_21_EU11-columnname.csv",
  "inst/extdata/regionmappingH12.csv",
  "LICENSE",
  "man/*",
  "NAMESPACE",
  "R/imports.R",
  "R/sysdata.rda",
  "README.md",
  "tests/.lintr",
  "vignettes/.lintr",
  "vignettes/madrat-workflow.png",
]
